# Max chain break block count at once
# 一次性可以连锁的最大数量
max-break: 64

# Enable diagonal block be counted
# 启用对角的方块连锁
diagonal-break: false

# Chain break groups
# when player has one of the tools in the list, and the block is in the list, the chain break will be enabled
# 连锁破坏组
# 当玩家有该组其中之一的工具时，并且方块属于该组中的方块时，连锁破坏将启用
groups:
  mine:
    # The permission required to use this group
    # if set null, "" , none, NONE or keep empty, the permission will be ignored
    # 使用此组所需的权限
    # 如果设置为null，""，none，NONE或保持为空，则将忽略此权限
    permission: lightchainbreak.group.mine
    tools:
      - DIAMOND_PICKAXE
      - IRON_PICKAXE
      - GOLDEN_PICKAXE
      - STONE_PICKAXE
      - WOODEN_PICKAXE
      - NETHERITE_PICKAXE
    target:
      - COAL_ORE
      - DEEPSLATE_COAL_ORE
      - IRON_ORE
      - DEEPSLATE_IRON_ORE
      - COPPER_ORE
      - DEEPSLATE_COPPER_ORE
      - GOLD_ORE
      - DEEPSLATE_GOLD_ORE
      - REDSTONE_ORE
      - DEEPSLATE_REDSTONE_ORE
      - EMERALD_ORE
      - DEEPSLATE_EMERALD_ORE
      - LAPIS_ORE
      - DEEPSLATE_LAPIS_ORE
      - DIAMOND_ORE
      - DEEPSLATE_DIAMOND_ORE
      - NETHER_GOLD_ORE
      - NETHER_QUARTZ_ORE
      - ANCIENT_DEBRIS
  wood:
    permission: lightchainbreak.group.wood
    tools:
      - DIAMOND_AXE
      - IRON_AXE
      - GOLDEN_AXE
      - STONE_AXE
      - WOODEN_AXE
      - NETHERITE_AXE
    target:
      - OAK_LOG
      - SPRUCE_LOG
      - BIRCH_LOG
      - JUNGLE_LOG
      - ACACIA_LOG
      - CHERRY_LOG
      - DARK_OAK_LOG
      - MANGROVE_LOG
